apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrpt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # personal email
    email: 'test@test.com'
    privateKeySecretRef:
      name: letsencrypt-pro
    solvers:
      - http01:
        ingress:
          class: nginx
    
